### ISSUE TITLE
No _slot_types in std_msgs.msg.Time

### ISSUE THREAD

**Issue by trainman419** [ros/std_msgs#6]
When I try to echo the nsecs field in a std_msgs/Time message, I get: 

```
 rostopic echo /clock/clock/nsecs
Traceback (most recent call last):
  File "/opt/ros/hydro/bin/rostopic", line 35, in <module>
    rostopic.rostopicmain()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostopic/__init__.py", line 1667, in rostopicmain
    _rostopic_cmd_echo(argv)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostopic/__init__.py", line 1027, in _rostopic_cmd_echo
    _rostopic_echo(topic, callback_echo, bag_file=options.bag)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostopic/__init__.py", line 694, in _rostopic_echo
    type_information = submsg_class._slot_types[index]
AttributeError: type object 'Time' has no attribute '_slot_types'
```

This also affects trying to plot the /clock topic using rqt_plot.

I'm trying to do this to debug suspected problems or jumps in the clock during bag file playback.

**Comment by dirk-thomas** [comment]
This is a bug in `rostopic echo`. Please try the fix from ros/ros_comm#414.

**Comment by trainman419** [comment]
I don't think this bug should bd addressed in rostopic echo, because it also affects rqt_plot.

ros/ros_comm#414 is creating a special case for genpy.TVal in rostopic, rather than fixing the Time or genpy.TVal class so that a special case isn't required.

**Comment by dirk-thomas** [comment]
Good point. I made an alternative PR in `genpy` (ros/genpy#29). Can you please verify that this works for you too - without the rostopic change of course?

**Comment by trainman419** [comment]
confirmed; this fixes topic introspection for me. Thanks!
