### ISSUE TITLE
MultiArrayLayout.data_offset is ambiguous

### ISSUE THREAD

**Issue by eric-wieser** [ros/std_msgs#9]
Here's the contents of `Int32MultiArray.msg`:

```
# Please look at the MultiArrayLayout message definition for
# documentation on all multiarrays.

MultiArrayLayout  layout        # specification of data layout
int32[]           data          # array of data
```

And here's the contents of `MultiArrayLayout`

```
# The multiarray declares a generic multi-dimensional array of a
# particular data type.  Dimensions are ordered from outer most
# to inner most.

MultiArrayDimension[] dim # Array of dimension properties
uint32 data_offset        # padding bytes at front of data                         (A)

# Accessors should ALWAYS be written in terms of dimension stride
# and specified outer-most dimension first.
# 
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]    (B)
<snip>
```

Uh oh - contradiction! Is `.layout.data_offset` the offset in bytes (A) or the offset in words (B)? If the former, how are we supposed to adjust for something unaligned like `data_offset = 3`?

**Comment by tfoote** [comment]
This is definitely ambiguous and there are arguments for both. I think this was mostly intended for supporting adding arbitrary header data in the front of the payload which would argue for bytes. But that's also not a recommended approach.

Similar to my comment in #9 I think that updating the docs to clearly mark this as deprecated might be the best approach.

**Comment by eric-wieser** [comment]
Mark the whole message as deprecated, or just this field?

**Comment by tfoote** [comment]
We reviewed this in the ROS team meeting and came to the conclusion that A is they typo assuming that the elements in the vector are of one byte(probably first written with uin8 or int8 datatypes. The underlying datastorage is a vector and it is not a supported vectors only support indexing by element. So an offset that is not an integral multiple of the element size is not valid. So we plan to update the documentation of (A) to be `padding of elements at front of data`. 

As referenced in #8 we're going to add documentation to indicate that the messages in this package are not expected to be heavily reused but are examples of datastructures and can be used for rapid prototyping.
